### ISSUE TITLE
Please consider renaming this  to: yarn-audit-parser 

### ISSUE THREAD

**Issue by frank-dspeed** [eclipse-theia/security-audit#13]
It took me relative to much time to audit what this is! I Would suggest renaming it to: yarn-audit-parser to make more clear what that is. 

I am Maintaining a lot of repos thats why i spotted this.

**Comment by vince-fugnitto** [comment]
The readme should have enough information on what the repository consists of, if not we can improve the description.
A rename should not be necessary.
